---
- name: Install Packages
  become: true
  apt:
    update_cache: yes
    state: latest
    pkg:
      - acl
      - python3-psycopg2
      - postgresql

- name: Fetch PostreSQL info
  become: true
  become_user: postgres
  postgresql_info:
    filter: ver*,ext*
  register: pginfo

- name: Create PostgreSQL configuration file
  become: true
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql__conf_path }}"
    mode: 0644
  notify: restart postgresql

- name: Configure databases and users
  become: true
  become_user: postgres
  block:
  - name: Create databases
    postgresql_db:
      name: "{{ item.name }}"
    loop: "{{ postgresql__databases | flatten(1) }}"
  - name: Create db users
    postgresql_user:
      name: "{{ item.name }}"
      db: "{{ item.db }}"
      password: "{{ item.password }}"
      comment: "{{ item.comment }}"
    loop: "{{ postgresql__users | flatten(1) }}"
  # TODO refine for different access types
  - name: Grant accesses
    postgresql_privs:
      db: "{{ item.db }}"
      privs: "{{ item.privs }}"
      role: "{{ item.role }}"
      type: "{{ item.type }}"
    loop: "{{ postgresql__privileges | flatten(1) }}"
  - name: Activate databases extensions
    postgresql_ext:
      name: "{{ item.name }}"
      db: "{{ item.db }}"
      cascade: "{{ item.cascade }}"
    loop: "{{ postgresql__extensions | flatten(1) }}"

- name: Enable and start Postgres
  become: true
  service:
    name: postgresql
    state: started
    enabled: yes
